name: anistats_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  data_access:
    path: ../data_access

  shared:
    path: ../shared

  go_router: ^13.2.0
  get_it: ^7.6.8

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true
