name: data_access
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-16.0.dev

# Add regular dependencies here.
dependencies:
  get_it: ^7.6.8
  uuid: ^4.3.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
